version: '3.9'
services:
  app:
    build:
      context: .
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - ./src:/dnprp-app
      - public-data:/dnprp-app/public
      - tmp-data:/dnprp-app/tmp
      - log-data:/dnprp-app/log
      - ./Gemfile:/dnprp-app/Gemfile
      - ./Gemfile.lock:/dnprp-app/Gemfile.lock
    depends_on:
      - db
  db:
    image: postgres:14.3
    env_file:
      - ./environments/db.env
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    build:
      context: ./nginx
    volumes:
      - public-data:/dnprp-app/public
      - tmp-data:/dnprp-app/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
