databases:
  - name: my_db
    databaseName: my_postgresql
    user: my_service
    region: singapore
    plan: free
services:
  - type: web
    name: my_service
    env: docker
    region: singapore
    branch: develop
    plan: free
    dockerfilePath: ./docker/deploy/staging/Dockerfile
    domains: # 独自ドメインを使う場合は設定する
      - xxxx.com 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my_db
          property: connectionString
      - key: CORS_ORIGINS # フロントエンドバックエンドでオリジンが異なる場合は設定する