databases:
  - name: rails-err
    databaseName: rails_err
    user: rails_err
    region: singapore

services:
  - type: web
    name: rails_err
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails_err
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

