default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('POSTGRES_USER') { 'default_user' } %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { 'default_password' } %>
  host: <%= ENV.fetch('DATABASE_HOSTNAME') { 'db' } %>

development:
  <<: *default
  database: dnprp_app_development

test:
  <<: *default
  database: dnprp_app_test

production:
  <<: *default
  # URLによる接続: DATABASE_URLが優先される。
  url: <%= ENV['DATABASE_URL'] %>
